---
- apt: name=supervisor
- file: state=directory path=/var/log/supervisor 

- file: state=directory path=/var/log/supervisor/{{supervisor_program}}
  when: supervisor_program is defined

- file: state=directory path=/var/log/supervisor/{{item.supervisor_program}}
  with_items: supervisor_programs

- copy: src=sigtrap.sh dest=/usr/local/bin owner=root group=root mode=0755

- include: programs.yml
  when: supervisor_program is defined or supervisor_programs is defined
