---
- apt:
    pkg: supervisor 
    name: "supervisor={{ supervisor_version }}"
- file: state=directory path=/var/log/supervisor 
- file: state=directory path=/var/log/supervisor/{{supervisor_program}}
- copy: src=sigtrap.sh dest=/usr/local/bin owner=root group=root mode=0755
- template: 
    src=supervisor.conf.j2
    dest=/etc/supervisor/conf.d/{{ supervisor_program }}.conf
  notify: restart supervisor
  when: "{{ supervisor_restart_on_finish | bool }}"

- template:
    src=supervisor.conf.j2
    dest=/etc/supervisor/conf.d/{{ supervisor_program }}.conf
  when: not "{{ supervisor_restart_on_finish | bool }}"
