---
# handlers file for example
- name: restart supervisor
  command: /bin/true
  notify:
    - stop supervisor
    - start supervisor

- name: stop supervisor
  service: name=supervisor state=stopped

- name: start supervisor
  service: name=supervisor state=started

- name: restart supervisor apps
  supervisorctl: name={{item.supervisor_program}} state=restarted
  with_items: supervisor_programs
